### ISSUE TITLE
Secure confirm_phone_by_code(code)

### ISSUE THREAD

**Issue by sqrtsanta** [kaikash/twilio_phone_verification#1]
Straight token comparing is not really safe, allowing some timing attacks.
There was [discussion](https://gist.github.com/josevalim/fb706b1e933ef01e4fb6#file-2_safe_token_authentication-rb-L20) when devise pull out token authentication, check it out for more details.

**Comment by kaikash** [comment]
As I understood I should use secure_compare instead of == compare. I will fix it soon. Thank you for support!

**Comment by kaikash** [comment]
v1.0.6 fixed this issue.
